### ISSUE TITLE
some gems fail to install, 'make' not found

### ISSUE THREAD

**Issue by canihavethisone** [puppets-epic-show-theatre/action-pdk-test-unit#4]
Unsure if there is a workaround (or me doing something wrong), or if **make** should be installed via the dockerfile or in the pdk source image.

In the meantime I have fallen back to using the following in my repo actions:

name: Run unit tests
    
```
    on:
      - push
      - pull_request
    
    jobs:
      validating:
        runs-on: ubuntu-latest
    
        steps:
        - name: Clone repository
          uses: actions/checkout@v2
        
        - name: Setup ruby
          uses: actions/setup-ruby@v1
          with:
            ruby-version: 2.5.9
    
        - name: Install bundler and gems
          run: |
            gem install bundler
            bundle install --jobs 4 --retry 3
    
        - name: Run unit tests
          run: |
            bundle exec rake rubocop
            bundle exec rake release_checks
```

**Comment by TuningYourCode** [comment]
Well, this github action just pulls in the puppetlabs pdk docker container and runs the pdk command.

We don't install any additional gems and as far as i know the pdk container should contain all needed once. It could be that puppetlabs published an broken pdk container but that would be out of our hands :)

**Comment by canihavethisone** [comment]
Ok, I wondered if that was the case.  However in your dockerfile are you able to ensure that **make** is installed/present?  If not, or if you don't think it's the right place to do so then just close this issue.

**Comment by TuningYourCode** [comment]
No, there is currently no option in this action to install any other packages inside the used docker image. But you can overwrite the used docker image. Probably @cdenneen can assist there but should be most likly something like
```
name: Run pdk test unit

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v2

    - name: Run unit tests
      uses: puppets-epic-show-theatre/action-pdk-test-unit@v1
      with:
        puppet-version: "7"
        build-args: PDKIMAGE=$your_dockerhub/container:version
```
Or just stick with your current solution. This github action is meant for simple use cases to test puppet modules. If you need any gems which require make it's probably not the right solution for that puppet module :)
